"""add_inventory_reservation_uq

Revision ID: 4b43faa5ba1b
Revises: 918bb029c2b0
Create Date: 2026-10-06 17:48:19.893290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b43faa5ba1b'
down_revision: Union[str, Sequence[str], None] = '918bb029c2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inventory_reservation_order_product_warehouse', 'inventory_reservations', ['order_id', 'product_id', 'warehouse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inventory_reservation_order_product_warehouse', 'inventory_reservations', type_='unique')
    # ### end Alembic commands ###
