"""add check constraint for non_negative_price

Revision ID: b5076370a551
Revises: 289eedb3f5d0
Create Date: 2026-10-03 09:18:07.841458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5076370a551'
down_revision: Union[str, Sequence[str], None] = '289eedb3f5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_product_price_non_negative', 'products', 'price >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_product_price_non_negative', 'products', type_='check')
    # ### end Alembic commands ###
